# Do: cpanm --installdeps .
requires 'Data::Compare';
requires 'DDP';
requires 'Path::ExpandTilde', '0.003'; # or newer
requires 'Data::Dumper::OneLine', '0.06'; # or newer
requires 'File::Inplace';
requires 'Set::Scalar';
