# Do: cpanm --installdeps .
requires 'DDP';
requires 'IPC::Open2';
requires 'Path::ExpandTilde', '0.003'; # or newer
requires 'Data::Dumper::OneLine', '0.06'; # or newer
requires 'File::Inplace';
requires 'Set::Scalar';
requires 'DBI';
requires 'DBD::SQLite';


requires 'Calendar::Any';
requires 'DateTime';
requires 'DateTime::Duration';
requires 'Text::Table';
requires 'Term::ANSIColor';

