#!/bin/bash

CONNECTED_DISPS=$(xrandr -q | perl -wlne "/^(?<disp>.+) connected/ and print $+{disp}")

if [[ -f ~/.screenlayout/dual.sh ]]; then
  ~/.screenlayout/dual.sh
elif [[ "$CONNECTED_DISPS" == *"HDMI-1"* ]]; then
  xrandr --output HDMI-1 --auto && xrandr --output eDP-1 --off
  pkill -USR1 polybar
  test -x ~/.fehbg && ~/.fehbg
fi

if [[ -f ~/.no-touchpad ]]; then
    ~/local/scripts/synclient/disable.sh
else
    ~/local/scripts/synclient/enable.sh
    ~/local/scripts/synclient/tap-to-click.sh
fi


