" ~/.vimrc
"
"  ageldama@gmail.com : 2006-11-16 12:36
"
"

" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'
"
" The bundles you install will be listed here
"
filetype plugin indent on
"
Bundle 'davidhalter/jedi-vim'
Bundle 'tpope/vim-fugitive'
"Bundle 'fholgado/minibufexpl.vim'
Bundle 'jlanzarotta/bufexplorer'
Bundle 'bling/vim-airline'
Bundle 'scrooloose/nerdtree'
Bundle 'kien/ctrlp.vim'
Bundle 'SirVer/ultisnips'
Bundle 'honza/vim-snippets'
Bundle 'ageldama/vim-ttfzoom'
"------------------------------------------------------------------------------

" use only Vim settings (instead of vi)
set nocompatible

" 문법강조
syntax on

" 줄번호
set number

" Row/Col?
set ruler

" 비쥬얼벨
set visualbell

" 자동들여쓰기 및 탭크기랑 <<, >> 크기조절.
"set autoindent
set noautoindent
"set smartindent
set nosmartindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab	" tab대신 스페이스!

" wrap? 그냥 보이는 것만 설정합니다.
set wrap

" textwidth : 자동으로 행을 자르기. 0이면 끄기.
set textwidth=999999

" modeline 향수
set showmode
set showcmd

" 검색
set hls
set incsearch
set ignorecase	" 대소문자무시
set scs	" smart-search

" 백스페이스 : 언제나, 심지어 내가 방금 입력한게 아닌 것도 지우도록-_-
set backspace=2

" 폰트
"set guifont=Consolas:h14:cANSI
"set guifont=Bitstream_Vera_Sans_Mono:h14:cANSI

" 메뉴&툴바
set guioptions=m

" 색상설정
"color koehler
if has('gui_running')
    colorscheme koehler
    set guifont=Monospace\ 11
else
    set bg=dark
endif

" 파일인코딩
set fencs=utf8,euc-kr

" 파일타입설정
filetype on
filetype indent on
filetype plugin on

" vim-jedi
let g:jedi#popup_on_dot=0   " it's faster. just use <C>-<SPACE> for the completion popup.


" Add the virtualenv's site-packages to vim path
python3 << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF


"
" http://unlogic.co.uk/2013/02/08/vim-as-a-python-ide/
" http://www.sontek.net/blog/2011/05/07/turning_vim_into_a_modern_python_ide.html#virtualenv
"


" airline
set laststatus=2

" minibufexplorer
"map <Leader>mbe :MBEOpen<cr>
"map <Leader>mbc :MBEClose<cr>
"map <Leader>mbt :MBEToggle<cr>




"EOF
