" ~/.vimrc
"
"  ageldama@gmail.com : 2006-11-16
"  ageldama@gmail.com : 2017-08-05
"  ageldama@gmail.com : 2018-03-24
"  ageldama@gmail.com : 2018-12-02
"

" https://github.com/VundleVim/Vundle.vim/issues/769#issue-188457119
" START - Setting up Vundle - the vim plugin bundler
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/Vundle.vim/README.md')
if !filereadable(vundle_readme)
  echo "Installing Vundle.."
  echo ""
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  let iCanHazVundle=0
endif
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
if iCanHazVundle == 0
  echo "Installing Bundles, please ignore key map error messages"
  echo ""
  :PluginInstall
endif
" END - Setting up Vundle - the vim plugin bundler

" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle required!
Bundle 'gmarik/vundle'
"
" The bundles you install will be listed here
"
filetype plugin indent on
"
"Bundle 'davidhalter/jedi-vim'
Bundle 'tpope/vim-fugitive'
Bundle 'airblade/vim-gitgutter'
"Bundle 'fholgado/minibufexpl.vim'
Bundle 'jlanzarotta/bufexplorer'

Bundle 'vim-airline/vim-airline'
"Bundle 'vim-airline/vim-airline-themes'

Bundle 'scrooloose/nerdtree'
"Bundle 'ctrlpvim/ctrlp.vim'
Bundle 'rbgrouleff/bclose.vim'
Bundle 't9md/vim-choosewin'

" :Ack and K
Bundle 'mileszs/ack.vim'

Bundle 'godlygeek/tabular'
"Bundle 'vim-syntastic/syntastic.git'

" :ALEInfo?
Bundle 'w0rp/ale'

" #, / and :Occur and :Moccur, <leader>oc and <leader>mo
Bundle 'vim-scripts/occur.vim'

"    start: <C-n> start multicursor and add a virtual cursor + selection on the match
"        next: <C-n> add a new virtual cursor + selection on the next match
"        skip: <C-x> skip the next match
"        prev: <C-p> remove current virtual cursor + selection and go back on previous match
"    select all: <A-n> start muticursor and directly select all matches
Bundle 'terryma/vim-multiple-cursors'

" yankstack
Bundle 'maxbrunsfeld/vim-yankstack'

Bundle 'ntpeters/vim-better-whitespace'

" Goyo
Bundle 'junegunn/goyo.vim'


" Golang
" FIXME: if filereadable("~/.vim/load-p/golang")
  Bundle 'fatih/vim-go'
  let g:go_auto_type_info = 1
"endif

"
Bundle 'majutsushi/tagbar'
Bundle 'junegunn/fzf.vim'


"Bundle "morhetz/gruvbox"
"color gruvbox
set bg=dark

" colorscheme
if 0
  Bundle 'NLKNguyen/papercolor-theme'

  set t_Co=256   " This is may or may not needed.

  set background=dark
  colorscheme PaperColor

  "let g:airline_theme='papercolor'
endif

" vim-choosewin
let g:choosewin_overlay_enable = 1
nmap  <leader>-  <Plug>(choosewin)


"------------------------------------------------------------------------------
"let mapleader = "\\"

set paste

if executable('rg')
  let g:ackprg = 'rg --vimgrep --no-heading'
  set grepprg=rg\ --vimgrep\ --no-heading
  set grepformat=%f:%l:%c:%m,%f:%l:%m
  "let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
elseif executable('ag')
  let g:ackprg = 'ag --vimgrep'
  set grepprg=ag\ --nogroup\ --nocolor
  "let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" yankstack
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste

" bind K to grep word under cursor
nnoremap <Leader>/ :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" xclip '\y'
vnoremap <silent><Leader>y :'<,'>w !xclip<CR>

" bind \ (backward slash) to grep shortcut
" command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!



" use only Vim settings (instead of vi)
set nocompatible

" 문법강조
syntax on

" 줄번호
set number

" Row/Col?
set ruler

" 비쥬얼벨
set visualbell

" 자동들여쓰기 및 탭크기랑 <<, >> 크기조절.
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab	" tab대신 스페이스!

" wrap? 그냥 보이는 것만 설정합니다.
set wrap

" textwidth : 자동으로 행을 자르기. 0이면 끄기.
set textwidth=250

" modeline 향수
set modeline

set showmode
set showcmd

" 검색
set hls
set incsearch
set ignorecase	" 대소문자무시
set scs	" smart-search

" 백스페이스 : 언제나, 심지어 내가 방금 입력한게 아닌 것도 지우도록-_-
set backspace=indent,eol,start


" 폰트
"set guifont=Consolas:h14:cANSI
"set guifont=Bitstream_Vera_Sans_Mono:h14:cANSI

" 메뉴&툴바
set guioptions=m

" 색상설정
if 1
  set t_Co=256
  "set t_AB=^[[48;5;%dm
  "set t_AF=^[[38;5;%dm
  if has('gui_running')
    set guifont=Noto\ Sans\ Mono\ CJK\ KR\ 10
    "set guifont=Inconsolata\ Medium\ 12
    "set guifont="Noto Sans Mono CJK KR 14"
    "color darkblue
    "set bg=light
  else
    "color default
    "set bg=dark
  endif
endif

" 파일인코딩
set fencs=utf8,euc-kr

" 파일타입설정
filetype on
filetype indent on
filetype plugin on

""""""""""""""""""""""""""""""
" => Visual mode related
""""""""""""""""""""""""""""""
" Visual mode pressing * or # searches for the current selection
" Super useful! From an idea by Michael Naumann
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>


" Close the current buffer
map <leader>bd :Bclose<cr>:tabclose<cr>gT

" Close all the buffers
map <leader>ba :bufdo bd<cr>

map <leader>] :bnext<cr>
map <leader>[ :bprevious<cr>

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>t<leader> :tabnext
map <leader>t[ :tabprev<cr>
map <leader>t] :tabnext<cr>

" Let 'tl' toggle between this and the last accessed tab
let g:lasttab = 1
nmap <Leader>tl :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()


" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/

" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>


" airline
set laststatus=2

" minibufexplorer
"map <Leader>mbe :MBEOpen<cr>
"map <Leader>mbc :MBEClose<cr>
"map <Leader>mbt :MBEToggle<cr>

" ALE
if 1
  let g:ale_sign_error = '>>'
  let g:ale_sign_warning = '--'
  let g:airline#extensions#ale#enabled = 1
  let g:ale_completion_enabled = 1
  let g:ale_enabled = 1
  let g:ale_open_list = 0
  autocmd BufRead,BufNewFile *.{java} let b:ale_enabled=0
endif

" Syntastic
if 0
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
endif

" PerlTidy
"define :Tidy command to run perltidy on visual selection || entire buffer"
command! -range=% -nargs=* PerlTidy <line1>,<line2>!perltidy
"run :Tidy on entire buffer and return cursor to (approximate) original position"
fun DoPerlTidy()
  let Pos = line2byte( line( "." ) )
  :PerlTidy
  exe "goto " . Pos
endfun

" Clipboard
set clipboard=unnamed



" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500



function! VisualSelection(direction, extra_filter) range
  let l:saved_reg = @"
  execute "normal! vgvy"

  let l:pattern = escape(@", "\\/.*'$^~[]")
  let l:pattern = substitute(l:pattern, "\n$", "", "")

  if a:direction == 'gv'
    call CmdLine("Ack '" . l:pattern . "' " )
  elseif a:direction == 'replace'
    call CmdLine("%s" . '/'. l:pattern . '/')
  endif

  let @/ = l:pattern
  let @" = l:saved_reg
endfunction

"EOF
