export PATH=$PATH:/home/jhyun/local/bin

export TERMINAL=konsole

export XMODIFIERS="@im=SCIM"
export QT_IM_MODULE=xim
export GTK_IM_MODULE=xim

scim -d 

#fcitx &

#exec gnome-session


~/.dropbox-dist/dropboxd &

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK GPG_AGENT_INFO GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
export SSH_AGENT_PID=$GNOME_KEYRING_PID



xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'


xgamma -gamma 0.6


xset s on
xset s 60

xautolock -time 1 -locker 'i3lock -c 000000 ' &


exec i3


###EOF
