#!/bin/sh

export PATH=$PATH:/home/jhyun/local/bin

#export TERMINAL=konsole
export TERMINAL=gnome-terminal

#export XMODIFIERS="@im=SCIM"
#export QT_IM_MODULE=scim
#export GTK_IM_MODULE=scim

#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE=ibus
#export GTK_IM_MODULE=ibus

export XMODIFIERS="@im=nabi"
export QT_IM_MODULE=xim
export GTK_IM_MODULE=xim

#scim -d 
#fcitx -d
nabi&
#ibus-daemon -d -x

# $ sudo pacman -S ibus ibus-qt ibus-hangul
#
#ibus-daemon&

#fcitx &

#exec gnome-session


~/.dropbox-dist/dropboxd &

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK GPG_AGENT_INFO GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
export SSH_AGENT_PID=$GNOME_KEYRING_PID



xmodmap -e 'keycode 66 = Control_L'
xmodmap -e 'clear Lock'
xmodmap -e 'add Control = Control_L'

# "xev" first.
xmodmap -e 'keycode 108 = Hangul'


synclient TapButton2=3


xgamma -gamma 0.6


xset s on
xset s 300

xautolock -time 5 -locker 'i3lock -c 000000 ' &
#xscreensaver &

pulseaudio --start &

# `systemd-journal` group
journalctl --no-pager -f --system --user | osd_cat -d 5 -s 3 -O 5 -l 20 -c green -A right -o 200 -f 7x13 &



exec i3


###EOF
