#!/bin/sh

#export LANG=ko_KR.UTF-8

export PATH=$PATH:/home/jhyun/local/bin

export TERMINAL=x-terminal-emulator

# ibus + hangul
export XMODIFIERS="@im=ibus"
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus

ibus-daemon -d -x

# ssh / gnome-keyring
dbus-update-activation-environment --systemd DISPLAY  # for `gnome-keyring-daemon'
eval $(dbus-launch /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

test -f ~/.dropbox-dist/dropboxd && ~/.dropbox-dist/dropboxd &

# "xev" first.
# xmodmap -e 'keycode 108 = Hangul'
test -f ~/.Xmodmap && xmodmap ~/.Xmodmap
# setxkbmap -option caps:super

xbindkeys &

#synclient TapButton2=3
#xgamma -gamma 0.6

xset b off
#xset s on
#xset s 300

xscreensaver -no-splash &

# Mute all audio input
pactl-mute.pl source all &

# NetworkManager
nm-applet &

# Redshift
redshift-gtk -l 37.566:126.977 & # Seoul

# Compositor
compton -b &

# Bluetooth
blueman-applet &

# Notification Logging
dbus-monitor "interface='org.freedesktop.Notifications', member='Notify'" >> /tmp/notifications-${USER}-${INVOCATION_ID}.log &

# Notification growl.
dunst &

# hotkeys
#sxhkd &

# panel + sys-tray
which xfce4-panel && xfce4-panel &
which lxpanel && lxpanel &

# bg-color
hsetroot -solid '#3f4058' &

# caps->ctrl
~/local/bin/caps-to-ctrl.sh 2 &

#
exec openbox


###EOF
