function zlogin_startx_dialog () {
    dialog --title "login" --timeout 5 --yesno "start X session? (5 secs auto-ok)" 6 45
    if [[ $? == 0 || $? == 255 ]]; then
      exec startx &> startx.log
    fi
}


if [[ -z $TMUX ]]; then
  if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    zlogin_startx_dialog
  fi
fi
