#!/bin/sh
export LANG=en_US.UTF-8

export PATH=$PATH:/home/jhyun/local/bin

#export TERMINAL=konsole
export TERMINAL=lxterminal

#export XMODIFIERS="@im=SCIM"
#export QT_IM_MODULE=scim
#export GTK_IM_MODULE=scim

#export XMODIFIERS="@im=ibus"
#export QT_IM_MODULE=ibus
#export GTK_IM_MODULE=ibus

export XMODIFIERS="@im=nabi"
export QT_IM_MODULE=xim
export GTK_IM_MODULE=xim

#scim -d 
#fcitx -d
nabi&
#ibus-daemon -d -x

# $ sudo pacman -S ibus ibus-qt ibus-hangul
#
#ibus-daemon&

#fcitx &


dbus-update-activation-environment --systemd DISPLAY
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

#~/.dropbox-dist/dropboxd &
# TODO: dropbox &

~/local/bin/caps-to-ctrl.sh


# "xev" first.
xmodmap -e 'keycode 108 = Hangul'


#xgamma -gamma 0.6


xset s on
xset s 300

xscreensaver -no-splash&
xautolock -time 5 -locker 'xscreensaver-command -lock ' &

dunst &

pulseaudio --start &
pacmd set-default-sink 7
# https://askubuntu.com/questions/71863/how-to-change-pulseaudio-sink-with-pacmd-set-default-sink-during-playback


#nm-applet &

redshift-gtk -l 37.566:126.977 & # Seoul
#redshift-gtk &

compton -b &


exec i3


###EOF
