#!/bin/bash

if [[ -z $STARTX_AUTO_ASKED ]] && [[ -z $DISPLAY ]] && [[ -z $SSH_TTY ]] && [[ -f ~/.use-startx-auto ]]; then
  dialog --title "login" --timeout 5 --yesno "start X session? (5 secs auto-ok)" 6 45
  if [[ $? == 0 || $? == 255 ]]; then
    if [[ -f ~/startx.log ]]; then
      rm -fv ~/startx.log
    fi
    export STARTX_AUTO_ASKED=1
    startx &> ~/startx.log
  fi
fi

export STARTX_AUTO_ASKED=1


