keymap="us.ctrl.kbd"

clear_tmp_enable="YES"

hostname="freebsd-macbook-air"

wlans_rtwn0="wlan0"
ifconfig_wlan0="WPA DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"


sshd_enable="YES"
ntpd_enable="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="NO"

kld_list="i915kms"

#nfs_client_enable="YES"
#rpc_lockd_enable="YES"
#rpc_statd_enable="YES"

performance_cx_lowest="Cmax"
economy_cx_lowest="Cmax"

nfs_client_enable="YES"
