#!/bin/sh

export TERMINAL=lxterminal

export XMODIFIERS="@im=ibus"
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus

ibus-daemon -d -x

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK GPG_AGENT_INFO GNOME_KEYRING_CONTROL GNOME_KEYRING_PID
export SSH_AGENT_PID=$GNOME_KEYRING_PID

#keychain ~/.ssh/id_rsa
#[ -f ~/.keychain/$HOSTNAME-sh ] && . ~/.keychain/$HOSTNAME-sh 2>/dev/null
#[ -f ~/.keychain/$HOSTNAME-sh-gpg ] && . ~/.keychain/$HOSTNAME-sh-gpg 2>/dev/null

#eval $(ssh-agent)


xset s on
xset s 300

xscreensaver -no-splash &


~/local/bin/caps-to-ctrl.sh 2s &

redshift-gtk &

exec i3


###EOF
