#!/bin/bash

if [[ -f ~/.bashrc ]]; then
    . ~/.bashrc
fi

if [[ $SHLVL = 1 ]] && [[ -z $SSH_TTY ]]; then

    prompt_timeout() {
        local msg="$1"
        local timeout="$2"
        local default="$3"
        local reply

        if read -t "$timeout" -p "$msg ($timeout seconds): " reply; then
            echo "$reply"
        else
            echo -e "\n[Timed out]"
            echo "$default"
        fi
    }

    if [[ -f ~/.use-fbterm-auto ]]; then
        confirm=$(prompt_timeout "Fbterm? (y/n)" 5 "y")
        if [[ "$confirm" == "y" || "$confirm" == "" ]]; then
            fbterm -n D2Coding -s 16 --font-width=8
        fi
    elif [[ -f ~/.use-startx-auto ]]; then
        confirm=$(prompt_timeout "Startx? (y/n)" 5 "y")
        if [[ "$confirm" == "y" || "$confirm" == "" ]]; then
            if [[ -f ~/startx.log ]]; then
                rm -fv ~/startx.log
            fi
            if [[ -f ~/.use-startx.log ]]; then
                startx &> ~/startx.log
            else
                startx
            fi
        fi
    fi
fi


