#!/bin/bash


export LESS='-R -i'
export PAGER=less
export EDITOR=run-editor.sh
#export EDITOR='emacsclient -a vim'

export PATH=$PATH:~/local/bin:~/.local/bin


if [[ -z "${PERL_LOCAL_LIB_ROOT}" ]]; then
  #echo perl-local-lib
  eval $(perl -Mlocal::lib)
fi

export PERLDOC="-MPod::Text::Color"


if [[ -d $HOME/bin ]]; then
  export PATH=$HOME/bin:$PATH
fi


if [[ -d $HOME/go/bin ]]; then
  export PATH=~/go/bin:$PATH
fi


eval "$(~/.local/bin/mise activate bash)"

if [[ -d ~/.local/share/mise/shims ]]; then
  export PATH=~/.local/share/mise/shims:$PATH
fi



if [ -x "$(command -v luarocks)" ]; then
  eval "$(luarocks path)"
fi



if [ "${-#*i}" == "$-" ]; then
    # echo non_interactive > /dev/stderr
    true
else
    alias tmux='tmux -2'
    alias view='vim -R'

    which bat >& /dev/null || which batcat >& /dev/null && alias bat=batcat
    which fdfind >& /dev/null && alias fd=fdfind

    if [[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]]; then
        source /usr/share/doc/fzf/examples/key-bindings.bash
    elif [[ -f /usr/share/fzf/shell/key-bindings.bash ]]; then
        source /usr/share/fzf/shell/key-bindings.bash
    fi

    if [ -x "$(command -v zoxide)" ]; then
        eval "$(zoxide init bash)"
    fi

    source ~/.bashrc.d/sensible.bash
    source ~/.bashrc.d/git-aliases.bash
    source ~/.bashrc.d/completion.bash
fi

