#!/bin/bash

path-append () {
    if ! echo "$PATH" | grep -Eq "(^|:)$1($|:)" ; then
        if [ "$2" = "before" ] ; then
            PATH="$1:$PATH"
        else
            PATH="$PATH:$1"
        fi
    fi
}

alias ls='ls --color'

export LESS='-R -i'
export PAGER=less
export EDITOR=run-editor.sh
#export EDITOR='emacsclient -a vim'

export PATH=~/local/bin:~/.local/bin:$PATH

if [[ -d $HOME/bin ]]; then
  export PATH=$HOME/bin:$PATH
fi

if [[ "${-#*i}" == "$-" ]]; then
    # echo non_interactive > /dev/stderr
    true
else


for i in ~/.bashrc.local.d/*; do
    [[ -f "$i" ]] && source "$i"
done

if [[ $PS1 ]]; then
  if [[ -f /usr/local/share/bash-completion/bash_completion.sh ]]; then
    source /usr/local/share/bash-completion/bash_completion.sh
  fi

  for i in /usr/local/etc/bash_completion.d/*; do
    [[ -f $i ]] && source $i
  done
fi
    alias tmux='tmux -2'
    alias view='vim -R'

    if [[ -x "$(command -v batcat)" ]]; then
      alias bat=batcat
    fi

    if [[ -x "$(command -v fdfind)" ]]; then
      alias fd=fdfind
    fi

    if (fzf --help | grep -- --bash) &> /dev/null ; then
        eval "$(eval fzf --bash)"
    else
        if [[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]]; then
            source /usr/share/doc/fzf/examples/key-bindings.bash
        elif [[ -f /usr/share/fzf/shell/key-bindings.bash ]]; then
            source /usr/share/fzf/shell/key-bindings.bash
        elif [[ -f /usr/share/fzf/key-bindings.bash ]]; then
            source /usr/share/fzf/key-bindings.bash
        fi
    fi

    source ~/.bashrc.d/sensible.bash
    source ~/.bashrc.d/git-aliases.bash
    source ~/.bashrc.d/completion.bash
    source ~/.bashrc.d/prompt.bash
    source ~/.bashrc.d/alias.bash

    if [[ -x "$(command -v zoxide)" ]]; then
        eval "$(zoxide init bash)"
    fi
fi


return 0

