#!/bin/sh

export PATH=$PATH:$HOME/local/bin

export TERMINAL=lxterminal

export XMODIFIERS="@im=ibus"
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus

ibus-daemon -d -x

dbus-update-activation-environment --systemd DISPLAY  # for `gnome-keyring-daemon'
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK


# "xev" first.
xmodmap -e 'keycode 108 = Hangul'


xscreensaver -no-splash &
xautolock -time 5 -locker 'xscreensaver-command -lock' &

pulseaudio --start &


~/local/bin/caps-to-ctrl.sh 2s &

pactl-mute.pl source all &

dunst &
redshift-gtk &

sxhkd &


exec openbox


###EOF
