#!/bin/sh

export PATH=$PATH:$HOME/local/bin

export TERMINAL=lxterminal

export XMODIFIERS="@im=ibus"
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus

ibus-daemon -d -x

dbus-update-activation-environment --systemd DISPLAY  # for `gnome-keyring-daemon'
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK


# "xev" first.
xmodmap -e 'keycode 108 = Hangul'

# no beep
xset -b &

xscreensaver -no-splash &
xautolock -time 5 -locker 'xscreensaver-command -lock' &

# Use `systemctl start --user pulseaudio` instead
# SEE: https://medium.com/@gamunu/enable-high-quality-audio-on-linux-6f16f3fe7e1f
# pulseaudio --start &


~/local/bin/caps-to-ctrl.sh 2s &

pactl-mute.pl source all &

NOTIFICATION_LOG=/tmp/notifications-${USER}-${INVOCATION_ID}.log
touch ${NOTIFICATION_LOG} && chmod 600 ${NOTIFICATION_LOG} && dbus-monitor "interface='org.freedesktop.Notifications', member='Notify'" >> ${NOTIFICATION_LOG} &

dunst &
redshift-gtk &
tint2 &

sxhkd &

hsetroot-solid.pl &

exec openbox


###EOF
